CREATE TABLE IF NOT EXISTS hits (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(255) NOT NULL,
    time_hit TIMESTAMP WITH TIME ZONE NOT NULL
);